version: '3.3'

services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_DB: my_store
      POSTGRES_USER: harold
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    #persistencia de la base de datos
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

